---

name:
  hs-backup
version:
  0.1.0.0
github:
  prikhi/hs-backup
homepage:
  https://github.com/prikhi/hs-backup#readme
license:
  GPL-3
author:
  Pavan Rikhi
maintainer:
  pavan.rikhi@gmail.com
copyright:
  2019 Pavan Rikhi
category:
  Backup
extra-source-files:
  - README.md
  - CHANGELOG.md
  - LICENSE


synopsis: Robust Backup Server for Resumeable, Archived Network Backups
description: >
    @hs-backup@ is a CLI backup server that leverages @rsync@ & @cp@ to make
    backups of network folders over SSH. It is fault-tolerant and will persist
    it's internal state so that backups are resumeable through network outages
    and system/service restarts.

    Backups are made with hourly, daily, monthly, and yearly frequencies. Data
    is de-duplicated by using the @link-dest@ rsync flag and hard-links for
    archives. The number of archived backups is automatically trimmed.

    @hs-backup@ is configured using a YAML file. By default, it attempts to
    load the configuration from @/etc/hs-backup.yaml@ but the @-c@ flag can be
    used to point the server to a different config location. There is an
    <https://github.com/prikhi/hs-backup/blob/master/example-hs-backup.yaml example configuration file>
    in the project's source repository.


ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints
  - -O2

dependencies:
  - base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - aeson
    - bytestring
    - cereal
    - cereal-text
    - cereal-time
    - directory
    - fast-logger
    - filepath
    - lifted-async
    - mtl
    - safe-exceptions
    - stm >= 2.5
    - text
    - time
    - typed-process
    - unix
    - yaml

executables:
  hs-backup:
    source-dirs: exe
    main: Main.hs
    dependencies:
      - hs-backup
      - cmdargs
    ghc-options:
      - -O2
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
