---

name:
  hs-backup
version:
  0.1.0.0
# synopsis:
# description:
homepage:
  https://github.com/prikhi/hs-backup#readme
license:
  GPL-3
author:
  Pavan Rikhi
maintainer:
  pavan.rikhi@gmail.com
copyright:
  2019 Pavan Rikhi
category:
  Web

extra-source-files:
  - README.md

dependencies:
  - base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  hs-backup:
    source-dirs: exe
    main: Main.hs
