---

name:
  hs-backup
version:
  0.1.0.0
# synopsis:
# description:
homepage:
  https://github.com/prikhi/hs-backup#readme
license:
  GPL-3
author:
  Pavan Rikhi
maintainer:
  pavan.rikhi@gmail.com
copyright:
  2019 Pavan Rikhi
category:
  Web

extra-source-files:
  - README.md
  - LICENSE

ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints
  - -O2

dependencies:
  - base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - aeson
    - bytestring
    - cereal
    - cereal-text
    - cereal-time
    - directory
    - fast-logger
    - filepath
    - lifted-async
    - mtl
    - safe-exceptions
    - stm >= 2.5
    - text
    - time
    - typed-process
    - yaml

executables:
  hs-backup:
    source-dirs: exe
    main: Main.hs
    dependencies:
      - hs-backup
      - cmdargs
    ghc-options:
      - -O2
      - -threaded
      - -with-rtsopts="-N"
